### ISSUE TITLE
GSoC Idea: Custom keyboard shortcuts

### ISSUE THREAD

**Issue by agarciamontoro** [mattermost/community#162]
### Summary

- Project Outcome: Design and implement a system to let users customize their keyboard shortcuts.
- Project Size: 350 hours
- Difficulty: Medium
- Mentor: Alejandro García Montoro (@agarciamontoro in Github, [@alejandro.garcia](https://community.mattermost.com/core/messages/@alejandro.garcia) in Mattermost)

### Description

Mattermost is built for developers. And we developers \*love\* to use keyboard shortcuts. And while both the web and the desktop applications have support for a wide variety of shortcuts, those are right now hardcoded in the product. Have you ever tried to agree with another developer on the best shortcut for any action? We have tried, and have started dozens of holy wars in the way.

That's why we have this project: we need a system to customize keyboard shortcuts per user. The main idea is to implement a new entry in the account settings that lets users individually override the shortcuts. We need to find a way of handling possible shortcut collisions, and to default to the original ones if no custom ones are defined.

### Project Goals

The key deliverable will be the code, tests and documentation for a new section in the user settings interface that will let users review and assign specific shortcuts to specific actions. This code will live in the core repository for the frontend: [mattermost-webapp](https://github.com/mattermost/mattermost-webapp).

Your solution should include the following capabilities:

- New user setting
  - Customize each keyboard shortcut defined in the product
  - Default to the hardcoded shortcut if no overwrite defined
  - Detect shortcut collision
- Use the customized shortcuts in the product
  - Dynamically show the defined shortcuts in the help modal
  - Listen for the defined shortcuts in the whole product

Optional features that can be added as a stretch goal include:
- Suggest similar keyboard shortcuts when a collision occurs
- Improve discoverability of shortcuts with hints in the product
- Add new, user-defined shortcuts for new actions

### Required Skills

- React / Redux, Typescript
- Go
- SQL
- REST
- UI/UX

**Comment by vorayash** [comment]
Hello sir, I want to contribute in this project. Can you please guide me how I can start?

**Comment by agarciamontoro** [comment]
Hi, @vorayash! I'd recommend to start following the steps in [this guide](https://developers.mattermost.com/contribute/gsoc/) and trying out [setting up the developer environment](https://developers.mattermost.com/contribute/server/developer-setup/).
