### ISSUE TITLE
GSoC Idea: CI pipeline analysis

### ISSUE THREAD

**Issue by agarciamontoro** [mattermost/community#169]
### Summary

- Project Outcome: Publish a plugin to analyze the CI pipelines in Mattermost to alert the team of build and test failures
- Project Size: 175 hours
- Difficulty: Easy
- Mentors: 
  - Ibrahim Acikgoz (@isacikgoz in Github, [@ibrahim.acikgoz](https://community.mattermost.com/core/messages/@ibrahim.acikgoz) in Mattermost)
  - Alejandro García Montoro (@agarciamontoro in Github, [@alejandro.garcia](https://community.mattermost.com/core/messages/@alejandro.garcia) in Mattermost)

### Description

Currently, the monitoring of the master branch of our [server repo](https://github.com/mattermost/mattermost-server) is done manually, fixing any test failures that could occur there. This is very time consuming and inefficient, and having this automated would help getting a more stable master branch, which will benefit the whole contributor community.

The project is to hook into CircleCI webhooks for success/failure for the master branch, and if a pipeline fails, extract the failed tests and post the contents to a Mattermost channel. If this first objective is done, we can extend the scope of the idea with some nice-to-have improvements: analytics on how much time each run took, analysis of which tests are flaky or a summary of how many times flaky tests failed.

### Project Goals

The key deliverable will be a GitHub repository that includes the code for the plugin and documentation for how to install, configure, and use it. This repository can be permanently hosted on the contributors profile or on the Mattermost GitHub organization depending on the contributor’s preferences. If time permits, a stretch goal will be to include the plugin in the official [Mattermost integrations marketplace](https://mattermost.com/marketplace/) to make it available by default on all Mattermost instances. If the feature is validated by Mattermost users, it might be also included in the core product.

Your solution should include the following capabilities:
- Hook into CircleCI webhooks for results of the master branch
- In case of failure:
  - Analyze the error
  - Extract the failed tests
  - Post the contents to a Mattermost channel

Optional features that can be added as a stretch goal include:
- Analytics on how much time each run took
- Analytics of the flaky tests:
  - Which tests are flaky
  - How many times every flaky test has failed

### Required Skills

- Go
- REST
- DevOps
- CircleCI

**Comment by abhinav700** [comment]
@agarciamontoro I would like to work on this project.

I don't know much about GSOC, so I don't know what is the exact procedure( whether I can start working on it right away or have to wait until I am assigned this project.)

I don't have any experience in devops as of now, So I think that it would be a great opportunity to learn some new skills.

**Comment by agarciamontoro** [comment]
Hey, @abhinav700, I'm sorry but these ideas were planned for last year's GSoC, for which Mattermost was not accepted as an organization. I'll close the issues now, sorry for the confusion!

If you're still interested in contributing to Mattermost, please feel free to browse [the main repo issues](https://github.com/mattermost/mattermost/issues). Thanks!
